PUT http://localhost:3003/api/blogs/5fb3ab944e7351ac164bb04e
Content-Type: application/json

{
    "title": "Tapanin blogi",
    "author": "Tapani",
    "url": "http://example.com/tapaani",
    "likes": 1
}